#include "cpu.h"

instruction_t cpu_instr_tbl[256] = {
    //? linha 0
    {"BRK", BRK, Implied, 7},
    {"ORA", ORA, INDX, 6},
    NO_INSTR,
    NO_INSTR,
    NO_INSTR,
    {"ORA", ORA, ZP, 3},
    {"ASL", ASL, ZP, 5},
    NO_INSTR,
    {"PHP", PHP, Implied, 3},
    {"ORA", ORA, IMM, 2},
    {"ASL", ASL, Accum, 2},
    NO_INSTR,
    NO_INSTR,
    {"ORA", ORA, Abs, 4},
    {"ASL", ASL, Abs, 6},
    NO_INSTR,

    //? linha 1
    {"BPL", BPL, Relative, 2},
    {"ORA", ORA, INDY, 5},
    NO_INSTR,
    NO_INSTR,
    NO_INSTR,
    {"ORA", ORA, ZPX, 4},
    {"ASL", ASL, ZPX, 6},
    NO_INSTR,
    {"CLC", CLC, Implied, 2},
    {"ORA", ORA, ABSY, 4},
    NO_INSTR,
    NO_INSTR,
    NO_INSTR,
    {"ORA", ORA, ABSX, 4},
    {"ASL", ASL, ABSX, 7},
    NO_INSTR,

    //?linha 2
    {"JSR", JSR, Abs, 6},
    {"AND", AND, INDX, 6},
    NO_INSTR,
    NO_INSTR,
    {"BIT", BIT, ZP, 3},
    {"AND", AND, ZP, 3},
    {"ROL", ROL, ZP, 5},
    NO_INSTR,
    {"PLP", PLP, Implied, 4},
    {"AND", AND, IMM, 2},
    {"ROL", ROL, Accum, 2},
    NO_INSTR,
    {"BIT", BIT, Abs, 4},
    {"AND", AND, Abs, 4},
    {"ROL", ROL, Abs, 6},
    NO_INSTR,

    //? linha 3
    {"BMI", BMI, Relative, 2},
    {"AND", AND, INDY, 5},
    NO_INSTR,
    NO_INSTR,
    NO_INSTR,
    {"AND", AND, ZPX, 4},
    {"ROL", ROL, ZPX, 6},
    NO_INSTR,
    {"SEC", SEC, Implied, 2},
    {"AND", AND, ABSY, 4},
    NO_INSTR,
    NO_INSTR,
    NO_INSTR,
    {"AND", AND, ABSX, 4},
    {"ROL", ROL, ABSX, 7},
    NO_INSTR,

    //? linha 4
    {"RTI", RTI, Implied, 6},
    {"EOR", EOR, INDX, 6},
    NO_INSTR,
    NO_INSTR,
    NO_INSTR,
    {"EOR", EOR, ZP, 3},
    {"LSR", LSR, ZP, 5},
    NO_INSTR,
    {"PHA", PHA, Implied, 3},
    {"EOR", EOR, IMM, 2},
    {"LSR", LSR, Accum, 2},
    NO_INSTR,
    {"JMP", JMP, Abs, 3},
    {"EOR", EOR, Abs, 4},
    {"LSR", LSR, Abs, 6},
    NO_INSTR,

    //? linha 5
    {"BVC", BVC, Relative, 2},
    {"EOR", EOR, INDY, 5},
    NO_INSTR,
    NO_INSTR,
    NO_INSTR,
    {"EOR", EOR, ZPX, 4},
    {"LSR", LSR, ZPX, 6},
    NO_INSTR,
    {"CLI", CLI, Implied, 2},
    {"EOR", EOR, Abs, 4},
    NO_INSTR,
    NO_INSTR,
    NO_INSTR,
    {"EOR", EOR, ABSX, 4},
    {"LSR", LSR, ABSX, 7},
    NO_INSTR,

    //? linha 6
    {"RTS", RTS, Implied, 6},
    {"ADC", ADC, INDX, 6},
    NO_INSTR,
    NO_INSTR,
    NO_INSTR,
    {"ADC", ADC, ZP, 3},
    {"ROR", ROR, ZP, 5},
    NO_INSTR,
    {"PLA", PLA, Implied, 4},
    {"ADC", ADC, IMM, 2},
    {"ROR", ROR, Accum, 2},
    NO_INSTR,
    {"JMP", JMP, IND, 5},
    {"ADC", ADC, Abs, 4},
    {"ROR", ROR, Abs, 6},
    NO_INSTR,

    //? linha 7
    {"BVS", BVS, Relative, 2},
    {"ADC", ADC, INDY, 5},
    NO_INSTR,
    NO_INSTR,
    NO_INSTR,
    {"ADC", ADC, ZPX, 4},
    {"ROR", ROR, ZPX, 6},
    NO_INSTR,
    {"SEI", SEI, Implied, 2},
    {"ADC", ADC, Abs, 4},
    NO_INSTR,
    NO_INSTR,
    NO_INSTR,
    {"ADC", ADC, ABSX, 4},
    {"ROR", ROR, ABSX, 7},
    NO_INSTR,

    //? linha 8
    NO_INSTR,
    {"STA", STA, INDX, 6},
    NO_INSTR,
    NO_INSTR,
    {"STY", STY, ZP, 3},
    {"STA", STA, ZP, 3},
    {"STX", STX, ZP, 3},
    NO_INSTR,
    {"DEY", DEY, Implied, 2},
    NO_INSTR,
    {"TXA", TXA, Implied, 2},
    NO_INSTR,
    {"STY", STY, Abs, 4},
    {"STA", STA, Abs, 4},
    {"STX", STX, Abs, 4},
    NO_INSTR,

    //? linha 9
    {"BCC", BCC, Relative, 2},
    {"STA", STA, INDY, 6},
    NO_INSTR,
    NO_INSTR,
    {"STY", STY, ZPX, 4},
    {"STA", STA, ZPX, 4},
    {"STX", STX, ZPY, 4},
    NO_INSTR,
    {"TYA", TYA, Implied, 2},
    {"STA", STA, ABSY, 5},
    {"TXS", TXS, Implied, 2},
    NO_INSTR,
    NO_INSTR,
    {"STA", STA, ABSX, 5},
    NO_INSTR,
    NO_INSTR,

    //? linha A
    {"LDY", LDY, IMM, 2},
    {"LDA", LDA, INDX, 6},
    {"LDX", LDX, IMM, 2},
    NO_INSTR,
    {"LDY", LDY, ZP, 3},
    {"LDA", LDA, ZP, 3},
    {"LDX", LDX, ZP, 3},
    NO_INSTR,
    {"TAY", TAY, Implied, 2},
    {"LDA", LDA, IMM, 2},
    {"TAX", TAX, Implied, 2},
    NO_INSTR,
    {"LDY", LDY, Abs, 4},
    {"LDA", LDA, Abs, 4},
    {"LDX", LDX, Abs, 4},
    NO_INSTR,

    //? linha B
    {"BCS", BCS, Relative, 2},
    {"LDA", LDA, INDY, 5},
    NO_INSTR,
    NO_INSTR,
    {"LDY", LDY, ZPX, 4},
    {"LDA", LDA, ZPX, 4},
    {"LDX", LDX, ZPY, 4},
    NO_INSTR,
    {"CLV", CLV, Implied, 2},
    {"LDA", LDA, ABSY, 4},
    {"TSX", TSX, Implied, 2},
    NO_INSTR,
    {"LDY", LDY, ABSX, 4},
    {"LDA", LDA, ABSX, 4},
    {"LDX", LDX, ABSY, 4},
    NO_INSTR,

    //? linha C
    {"CPY", CPY, IMM, 2},
    {"CMP", CMP, INDX, 6},
    NO_INSTR,
    NO_INSTR,
    {"CPY", CPY, ZP, 3},
    {"CMP", CMP, ZP, 3},
    {"DEC", DEC, ZP, 5},
    NO_INSTR,
    {"INY", INY, Implied, 2},
    {"CMP", CMP, IMM, 2},
    {"DEX", DEX, Implied, 2},
    NO_INSTR,
    {"CPY", CPY, Abs, 4},
    {"CMP", CMP, Abs, 4},
    {"DEC", DEC, Abs, 6},
    NO_INSTR,

    //? linha D
    {"BNE", BNE, Relative, 2},
    {"CMP", CMP, INDY, 5},
    NO_INSTR,
    NO_INSTR,
    NO_INSTR,
    {"CMP", CMP, ZPX, 4},
    {"DEC", DEC, ZP, 6},
    NO_INSTR,
    {"CLD", CLD, Implied, 2},
    {"CMP", CMP, ABSY, 4},
    NO_INSTR,
    NO_INSTR,
    NO_INSTR,
    {"CMP", CMP, ABSX, 4},
    {"DEC", DEC, ABSX, 7},
    NO_INSTR,

    //? linha E
    {"CPX", CPX, IMM, 2},
    {"SBC", SBC, INDX, 6},
    NO_INSTR,
    NO_INSTR,
    {"CPX", CPX, ZP, 3},
    {"SBC", SBC, ZP, 3},
    {"INC", INC, ZP, 5},
    NO_INSTR,
    {"INX", INX, Implied, 2},
    {"SBC", SBC, IMM, 2},
    {"NOP", NOP, Implied, 2},
    NO_INSTR,
    {"CPX", CPX, Abs, 4},
    {"SBC", SBC, Abs, 4},
    {"INC", INC, Abs, 6},
    NO_INSTR,

    //? linha F
    {"BEQ", BEQ, Relative, 2},
    {"SBC", SBC, INDY, 5},
    NO_INSTR,
    NO_INSTR,
    NO_INSTR,
    {"SBC", SBC, ZPX, 4},
    {"INC", INC, ZPX, 6},
    NO_INSTR,
    {"SED", SED, Implied, 2},
    {"SBC", SBC, ABSY, 4},
    NO_INSTR,
    NO_INSTR,
    NO_INSTR,
    {"SBC", SBC, ABSX, 4},
    {"INC", INC, ABSX, 7},
    NO_INSTR,
};